### ISSUE TITLE
Refactor to separate lib and CLI?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/cffconvert#276]
Howdy @jspaaks 👋,

I'm currently working on a [project](https://software-metadata.pub) aiming to automate compiling software metadata from different sources in a source code repo, including `CITATION.cff`. The internal data model is based on CodeMeta, and I'd like to use `cffconvert` programatically to do the CFF-CM conversion.

Currently, the architecture of `cffconvert` makes that a bit cumbersome, as it is intended to be used as CLI only, so I'm wondering whether it would be possible to refactor the conversion logic to a separate library package, or an API module, that both `cffconvert` CLI and third-party packages can use?

Personally, I have some resources to work on this, and the possibility to enlist some further help (both to an extent), but first would like to assess whether this is something that would be a) useful and b) possible.

**Comment by sdruskat** [comment]
Okay, just experimented again, and, given a CFF file, this actually only boils down to 

```python
citation = cffconvert.cli.create_citation.create_citation(infile, None)
codemeta_str = citation.as_schemaorg()
```

Fair enough, although a dedicated API would be nicer to work with, e.g., `codemeta_str = cffconvert.convert(cff_dict, 'CodeMeta')` (and the dependency would be smaller if cffconvertlib was an extra package...).
Happy to discuss this further, or for the issue to be closed if it is decided it's good enough as is.

**Comment by sdruskat** [comment]
> Maybe I should document the API :)

Yes, or that 😆.
 
> I think I would use `cffconvert` like this for your use case:
> 
> ```python
> from cffconvert import Citation
> with open('CITATION.cff', 'rt') as f:
>     cffstr = f.read()
> codemeta_str = Citation(cffstr).as_codemeta()
> ```

👍 

Feel free to close as my immediate concern is solved, or leave open if such a refactoring is something that would be useful...

**Comment by jspaaks** [comment]
Closing for now, the refactoring that I've done recently in #345 and #350 is probably as much as I want to have for the moment.
